CLASS zcl_oo_polimorphism_sub2 DEFINITION INHERITING FROM zcl_oo_polimorphism_sub
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_OO_POLIMORPHISM_SUB2 IMPLEMENTATION.
ENDCLASS.
