CLASS zcl_oo_polimorphism_sub DEFINITION INHERITING FROM zcl_oo_polimorphism_super
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_OO_POLIMORPHISM_SUB IMPLEMENTATION.
ENDCLASS.
