CLASS zcl_oo_polimorphism_super DEFINITION
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_OO_POLIMORPHISM_SUPER IMPLEMENTATION.
ENDCLASS.
