CLASS zcl_oo_polimorphism_super DEFINITION
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_oo_polimorphism_super IMPLEMENTATION.
ENDCLASS.
